# Generated by Django 3.2.7 on 2021-09-21 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(max_length=20)),
                ('ten', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tiem', models.DateTimeField(default=django.utils.timezone.now)),
                ('noi_tiem', models.CharField(max_length=100)),
                ('dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiemchung.dan')),
            ],
        ),
    ]
