# Generated by Django 3.2.7 on 2021-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiemchung', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dan',
            options={'verbose_name_plural': 'Dan'},
        ),
        migrations.AlterModelOptions(
            name='tiem',
            options={'verbose_name_plural': 'Tiem'},
        ),
        migrations.AlterField(
            model_name='dan',
            name='cccd',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
