# Generated by Django 3.2.7 on 2021-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiemchung', '0002_auto_20210921_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dan',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
